### ISSUE TITLE
Incompatibility with "Type Linting" feature

### ISSUE THREAD

**Issue by herrlegno** [Akronae/eslint-plugin-exception-handling#6]
## Expected Behavior
Work fine

## Actual Behavior
Eslint throws error

![image](https://github.com/user-attachments/assets/54da0293-18de-4e0c-926a-becf11d95418)

## Steps to Reproduce the Problem

  1. clone https://github.com/herrlegno/eslint-plugin-exception-handling
  2. execute `npm run lint`

**Comment by Akronae** [comment]
Hi @herrlegno,

Thanks a lot for your detailed submission!
I'm going to look into it as soon as I have some spare time.

**Comment by Akronae** [comment]
@herrlegno should be fixed in v1.4.4
Thanks for the report!
Please let me know if I can close this.

**Comment by herrlegno** [comment]
@Akronae It is working, thank you! I'll close this now and I'll delete the repo!
