### ISSUE TITLE
Rules are making eslint crash

### ISSUE THREAD

**Issue by herrlegno** [Akronae/eslint-plugin-exception-handling#7]
## Description

Error doesn't provide any useful information

## Steps to Reproduce

1. Clone [repo](https://github.com/herrlegno/exception-handling-eslint-error)
2. Run `npm run lint`

## Screenshots

![imagen](https://github.com/user-attachments/assets/100e55cc-23d3-44c6-a200-39f087821f22)

## Expected Behavior

Not to crash eslint

## Actual Behavior

Crash eslint

**Comment by Akronae** [comment]
Hey @herrlegno 👋 

After some investigation I found the root of the issue.
Should be fixed on `v1.5.3`.
Thanks for helping make the code more reliable !

I let you confirm it's working well and close the issue 😃

**Comment by Akronae** [comment]
Great! Usually restarting eslint is a good idea (`ctrl + shift + p` if you're on vscode) :p  

![image](https://github.com/user-attachments/assets/5929a6fa-0354-4057-a00b-6a39bd056eea)
